# docker image name
image: golang

# some variables
variables:
  REPO_NAME: debug

# go mod cache
.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

# some settings
before_script:
  - go env -w GO111MODULE=on
  - go env -w GOPROXY="https://goproxy.io,direct"

stages:
  - test
  - build
  - deploy

# test branch
format:
  stage: test
  tags:
    - edte
  script:
    - cd $GOPATH/src/$REPO_NAME
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

# build branch
compile:
  stage: build
  extends: .go-cache
  script:
    - go mod tidy
    - go build -race -o $REPO_NAME
  artifacts:
    paths:
      - $REPO_NAME

# deploy branch
docker:
  stage: deploy
  when: manual
  tags:
    - edte
  script:
    ./app
