language:
  - go

branchs:
  only:
    - master
env:
  - GO111MODULE=on


before_install:


install:
  - go mod tidy

before_script:


scrip:
  - go build main.go

after_success:

  - before_deploy:


  - deploy:

  - after_deploy:

  - after_script:

after_failure:
